# Generated by Django 3.1 on 2022-05-18 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_edited', to=settings.AUTH_USER_MODEL)),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('create', 'Can create a new article'), ('edit', 'Can edit an article'), ('approve/reject', 'Can approve or reject an article')],
            },
        ),
    ]
